name: Bawks - Doing Stuff Organization

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: NONPROD
      url: https://github.com
    steps:
      - uses: actions/checkout@v2

      - name: Staging
        run: mkdir aws_lambda_layer

      # - name: Python Virtual Environment
      #   run: |
      #     python3 -m venv .venv
      #     source .venv/bin/activate

      - name: Install Requirements
        run: pip3 install -r requirements.txt --target ./aws_lambda_layer

      - name: Create Zip of Dependencies
        run: |
          cd aws_lambda_layer
          zip -r9 ./../lambda_layer.zip .

      - uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: ./lambda_layer.zip

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
            aws s3 cp ./lambda_layer.zip s3://bawks-awesome-python-layer
            aws lambda publish-layer-version --layer-name my-layer --description "My layer" --content S3Bucket=bawks-awesome-python-layer,S3Key=lambda_layer.zip --compatible-runtimes "python3.8" "python3.9"
